### ISSUE TITLE
Compatibility with gecode-5.0.0

### ISSUE THREAD

**Issue by sagitter** [ampl/mp#109]
Hi all.

`mp` does not compile with latest released `gecode-5.0.0`: 

```
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:97:11: note:   no known conversion for argument 2 from '<unresolved overloaded function type>' to 'mp::MPToGecodeConverter::VarArgFunc {aka void (*)(Gecode::Home, const Gecode::IntVarArgs&, Gecode::IntVar, int)}'
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:188:8: note: candidate: void mp::MPToGecodeConverter::Convert(const Problem&)
   void Convert(const Problem &p);
        ^~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:188:8: note:   candidate expects 1 argument, 2 provided
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h: In member function 'mp::LinExpr mp::MPToGecodeConverter::VisitMax(mp::IteratedExpr)':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:226:34: error: no matching function for call to 'mp::MPToGecodeConverter::Convert(mp::IteratedExpr&, <unresolved overloaded function type>)'
     return Convert(e, Gecode::max);
                                  ^
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:91:12: note: candidate: mp::MPToGecodeConverter::BoolExpr mp::MPToGecodeConverter::Convert(Gecode::BoolOpType, mp::BasicExprVisitor<mp::MPToGecodeConverter, Gecode::LinIntExpr, mp::internal::ExprTypes>::IteratedLogicalExpr)
   BoolExpr Convert(Gecode::BoolOpType op, IteratedLogicalExpr e);
            ^~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:91:12: note:   no known conversion for argument 1 from 'mp::IteratedExpr {aka mp::BasicIteratedExpr<mp::BasicExpr<(mp::expr::Kind)1, (mp::expr::Kind)47>, (mp::expr::Kind)42, (mp::expr::Kind)45>}' to 'Gecode::BoolOpType'
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:97:11: note: candidate: mp::LinExpr mp::MPToGecodeConverter::Convert(mp::IteratedExpr, mp::MPToGecodeConverter::VarArgFunc)
   LinExpr Convert(IteratedExpr e, VarArgFunc f);
           ^~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:97:11: note:   no known conversion for argument 2 from '<unresolved overloaded function type>' to 'mp::MPToGecodeConverter::VarArgFunc {aka void (*)(Gecode::Home, const Gecode::IntVarArgs&, Gecode::IntVar, int)}'
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:188:8: note: candidate: void mp::MPToGecodeConverter::Convert(const Problem&)
   void Convert(const Problem &p);
        ^~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:188:8: note:   candidate expects 1 argument, 2 provided
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h: At global scope:
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:300:11: error: 'IntConLevel' in namespace 'Gecode' does not name a type
   Gecode::IntConLevel icl_;
           ^~~~~~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:377:16: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   typedef std::auto_ptr<GecodeProblem> ProblemPtr;
                ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from /builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:26,
                 from /builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:23:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:23:0:
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:387:11: error: 'IntConLevel' in namespace 'Gecode' does not name a type
   Gecode::IntConLevel icl() const { return icl_; }
           ^~~~~~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:41:63: error: 'ICL_VAL' is not a member of 'Gecode'
   {"val", "value propagation or consistency (naive)", Gecode::ICL_VAL},
                                                               ^~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:41:63: note: suggested alternative: 'IPL_VAL'
   {"val", "value propagation or consistency (naive)", Gecode::ICL_VAL},
                                                               ^~~~~~~
                                                               IPL_VAL
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:42:63: error: 'ICL_BND' is not a member of 'Gecode'
   {"bnd", "bounds propagation or consistency",        Gecode::ICL_BND},
                                                               ^~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:42:63: note: suggested alternative: 'IPL_BND'
   {"bnd", "bounds propagation or consistency",        Gecode::ICL_BND},
                                                               ^~~~~~~
                                                               IPL_BND
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:43:63: error: 'ICL_DOM' is not a member of 'Gecode'
   {"dom", "domain propagation or consistency",        Gecode::ICL_DOM},
                                                               ^~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:43:63: note: suggested alternative: 'IPL_DOM'
   {"dom", "domain propagation or consistency",        Gecode::ICL_DOM},
                                                               ^~~~~~~
                                                               IPL_DOM
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:44:63: error: 'ICL_DEF' is not a member of 'Gecode'
   {"def", "the default consistency for a constraint", Gecode::ICL_DEF}
                                                               ^~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:44:63: note: suggested alternative: 'IPL_DEF'
   {"def", "the default consistency for a constraint", Gecode::ICL_DEF}
                                                               ^~~~~~~
                                                               IPL_DEF
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:235:52: error: 'Gecode::IntConLevel' has not been declared
 GecodeProblem::GecodeProblem(int num_vars, Gecode::IntConLevel icl) :
                                                    ^~~~~~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc: In constructor 'mp::GecodeProblem::GecodeProblem(int, int)':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:236:55: error: class 'mp::GecodeProblem' does not have any field named 'icl_'
   vars_(space(), num_vars), obj_irt_(Gecode::IRT_NQ), icl_(icl) {
                                                       ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc: In constructor 'mp::GecodeProblem::GecodeProblem(bool, mp::GecodeProblem&)':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:240:50: error: class 'mp::GecodeProblem' does not have any field named 'icl_'
   Gecode::Space(share, s), obj_irt_(s.obj_irt_), icl_(s.icl_) {
                                                  ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:240:57: error: 'class mp::GecodeProblem' has no member named 'icl_'
   Gecode::Space(share, s), obj_irt_(s.obj_irt_), icl_(s.icl_) {
                                                         ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc: In member function 'virtual void mp::GecodeProblem::constrain(const Gecode::Space&)':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:258:55: error: 'icl_' was not declared in this scope
         static_cast<const GecodeProblem&>(best).obj_, icl_);
                                                       ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc: In member function 'Gecode::BoolExpr mp::MPToGecodeConverter::Convert(Gecode::BoolOpType, mp::BasicExprVisitor<mp::MPToGecodeConverter, Gecode::LinIntExpr, mp::internal::ExprTypes>::IteratedLogicalExpr)':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:268:53: error: 'icl_' was not declared in this scope
     args[index] = Gecode::expr(problem_, Visit(*i), icl_);
                                                     ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:271:32: error: 'icl_' was not declared in this scope
   rel(problem_, op, args, var, icl_);
                                ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc: In member function 'mp::LinExpr mp::MPToGecodeConverter::Convert(mp::IteratedExpr, mp::MPToGecodeConverter::VarArgFunc)':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:278:47: error: 'icl_' was not declared in this scope
     args << Gecode::expr(problem_, Visit(*i), icl_);
                                               ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:280:29: error: 'icl_' was not declared in this scope
   f(problem_, args, result, icl_);
                             ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc: At global scope:
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:310:9: error: 'IntConLevel' in namespace 'Gecode' does not name a type
 Gecode::IntConLevel MPToGecodeConverter::GetICL(int con_index) const {
         ^~~~~~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc: In member function 'void mp::MPToGecodeConverter::Convert(const Problem&)':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:350:13: error: 'IntConLevel' in namespace 'Gecode' does not name a type
     Gecode::IntConLevel &icl_;
             ^~~~~~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:351:13: error: 'IntConLevel' in namespace 'Gecode' does not name a type
     Gecode::IntConLevel saved_value_;
             ^~~~~~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:354:35: error: expected ')' before '&' token
     ICLSetter(Gecode::IntConLevel &icl, Gecode::IntConLevel new_value) :
                                   ^
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc: In destructor 'mp::MPToGecodeConverter::Convert(const Problem&)::ICLSetter::~ICLSetter()':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:358:20: error: 'icl_' was not declared in this scope
     ~ICLSetter() { icl_ = saved_value_; }
                    ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:358:27: error: 'saved_value_' was not declared in this scope
     ~ICLSetter() { icl_ = saved_value_; }
                           ^~~~~~~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:358:27: note: suggested alternative: 'si_value'
     ~ICLSetter() { icl_ = saved_value_; }
                           ^~~~~~~~~~~~
                           si_value
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc: In member function 'void mp::MPToGecodeConverter::Convert(const Problem&)':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:367:26: error: 'icl_' was not declared in this scope
     ICLSetter icl_setter(icl_, GetICL(i));
                          ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:367:32: error: 'GetICL' was not declared in this scope
     ICLSetter icl_setter(icl_, GetICL(i));
                                ^~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:389:26: error: 'icl_' was not declared in this scope
     ICLSetter icl_setter(icl_, GetICL(p.num_algebraic_cons() + i));
                          ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:389:32: error: 'GetICL' was not declared in this scope
     ICLSetter icl_setter(icl_, GetICL(p.num_algebraic_cons() + i));
                                ^~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc: In member function 'mp::LinExpr mp::MPToGecodeConverter::VisitIf(mp::BasicExprVisitor<mp::MPToGecodeConverter, Gecode::LinIntExpr, mp::internal::ExprTypes>::IfExpr)':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:425:67: error: 'icl_' was not declared in this scope
       Gecode::channel(problem_, Gecode::expr(problem_, condition, icl_), result);
                                                                   ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:430:48: error: 'icl_' was not declared in this scope
       Gecode::expr(problem_, Visit(then_expr), icl_),
                                                ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc: In member function 'mp::LinExpr mp::MPToGecodeConverter::VisitCount(mp::BasicExprVisitor<mp::MPToGecodeConverter, Gecode::LinIntExpr, mp::internal::ExprTypes>::CountExpr)':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:453:53: error: 'icl_' was not declared in this scope
     args[index] = Gecode::expr(problem_, Visit(*i), icl_);
                                                     ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:456:58: error: 'icl_' was not declared in this scope
   Gecode::linear(problem_, args, Gecode::IRT_EQ, result, icl_);
                                                          ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc: In member function 'mp::LinExpr mp::MPToGecodeConverter::VisitNumberOf(mp::IteratedExpr)':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:468:59: error: 'icl_' was not declared in this scope
     args[i - 1] = Gecode::expr(problem_, Visit(e.arg(i)), icl_);
                                                           ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:469:65: error: 'icl_' was not declared in this scope
   count(problem_, args, Gecode::expr(problem_, Visit(e.arg(0)), icl_),
                                                                 ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc: In member function 'Gecode::BoolExpr mp::MPToGecodeConverter::LogicalExprConverter::VisitAllDiff(mp::BasicExprVisitor<mp::MPToGecodeConverter::LogicalExprConverter, Gecode::BoolExpr, mp::internal::ExprTypes>::PairwiseExpr)':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:495:70: error: 'class mp::MPToGecodeConverter' has no member named 'icl_'
       logical_args[index++] = Gecode::expr(problem, expr, converter_.icl_);
                                                                      ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:500:37: error: 'class mp::MPToGecodeConverter' has no member named 'icl_'
       logical_args, var, converter_.icl_);
                                     ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc: In constructor 'mp::GecodeSolver::GecodeSolver()':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:597:3: error: class 'mp::GecodeSolver' does not have any field named 'icl_'
   icl_(Gecode::ICL_DEF),
   ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:597:16: error: 'ICL_DEF' is not a member of 'Gecode'
   icl_(Gecode::ICL_DEF),
                ^~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:597:16: note: suggested alternative: 'IPL_DEF'
   icl_(Gecode::ICL_DEF),
                ^~~~~~~
                IPL_DEF
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:632:44: error: 'IntConLevel' is not a member of 'Gecode'
       &GecodeSolver::GetEnumOption<Gecode::IntConLevel>,
                                            ^~~~~~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:632:44: note: suggested alternative: 'IntPropLevel'
       &GecodeSolver::GetEnumOption<Gecode::IntConLevel>,
                                            ^~~~~~~~~~~
                                            IntPropLevel
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:632:44: error: 'IntConLevel' is not a member of 'Gecode'
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:632:44: note: suggested alternative: 'IntPropLevel'
       &GecodeSolver::GetEnumOption<Gecode::IntConLevel>,
                                            ^~~~~~~~~~~
                                            IntPropLevel
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:633:44: error: 'IntConLevel' is not a member of 'Gecode'
       &GecodeSolver::SetEnumOption<Gecode::IntConLevel>,
                                            ^~~~~~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:633:44: note: suggested alternative: 'IntPropLevel'
       &GecodeSolver::SetEnumOption<Gecode::IntConLevel>,
                                            ^~~~~~~~~~~
                                            IntPropLevel
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:633:44: error: 'IntConLevel' is not a member of 'Gecode'
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:633:44: note: suggested alternative: 'IntPropLevel'
       &GecodeSolver::SetEnumOption<Gecode::IntConLevel>,
                                            ^~~~~~~~~~~
                                            IntPropLevel
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:634:8: error: 'icl_' was not declared in this scope
       &icl_, INT_CON_LEVELS);
        ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc: In member function 'void mp::GecodeSolver::Solve(mp::Problem&, mp::SolutionHandler&)':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:778:47: error: 'icl_' was not declared in this scope
   MPToGecodeConverter converter(p.num_vars(), icl_);
                                               ^~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:821:64: error: no matching function for call to 'mp::GecodeSolver::Search<Gecode::RBS>(mp::Problem&, mp::GecodeProblem&, Gecode::Search::Statistics&, mp::SolutionHandler&)'
     solution = Search<Gecode::RBS>(p, gecode_problem, stats, sh);
                                                                ^
In file included from /builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:23:0:
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:381:14: note: candidate: template<template<template<template<class> class<template-parameter-2-1>, class> template<class> class<template-parameter-2-1>, class> class Meta> mp::GecodeSolver::ProblemPtr mp::GecodeSolver::Search(mp::Problem&, mp::GecodeProblem&, Gecode::Search::Statistics&, mp::SolutionHandler&)
   ProblemPtr Search(Problem &p, GecodeProblem &gecode_problem,
              ^~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:381:14: note:   template argument deduction/substitution failed:
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:824:74: error: no matching function for call to 'mp::GecodeSolver::Search<Gecode::Driver::EngineToMeta>(mp::Problem&, mp::GecodeProblem&, Gecode::Search::Statistics&, mp::SolutionHandler&)'
         Search<Gecode::Driver::EngineToMeta>(p, gecode_problem, stats, sh);
                                                                          ^
In file included from /builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.cc:23:0:
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:381:14: note: candidate: template<template<template<template<class> class<template-parameter-2-1>, class> template<class> class<template-parameter-2-1>, class> class Meta> mp::GecodeSolver::ProblemPtr mp::GecodeSolver::Search(mp::Problem&, mp::GecodeProblem&, Gecode::Search::Statistics&, mp::SolutionHandler&)
   ProblemPtr Search(Problem &p, GecodeProblem &gecode_problem,
              ^~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/solvers/gecode/gecode.h:381:14: note:   template argument deduction/substitution failed:
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/test/asl/aslproblem-test.cc: In member function 'virtual void SuffixTest_FindSuffix_Test::TestBody()':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/test/asl/aslproblem-test.cc:546:8: warning: suggest explicit braces to avoid ambiguous 'else' [-Wdangling-else]
     if (kinds[i] != kind)
        ^
[ 76%] Linking CXX executable ../bin/safeint-test
cd /builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/build/test && /usr/bin/cmake -E cmake_link_script CMakeFiles/safeint-test.dir/link.txt --verbose=1
/usr/bin/c++   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wall -Wextra -pedantic -DNDEBUG  -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld CMakeFiles/safeint-test.dir/safeint-test.cc.o  -o ../bin/safeint-test -Wl,-rpath,/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/build/bin -rdynamic ../lib/libgtest-extra.a ../bin/libmp.so.3.1.0 -lpthread /usr/lib64/librt.so 
In file included from /builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/include/mp/problem-builder.h:34:0,
                 from /builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/test/../src/problem.cc:24,
                 from /builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/test/problem-test.cc:42:
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/include/mp/nl-reader.h: In member function 'void mp::internal::NLReader<Reader, Handler>::ReadBounds() [with BoundHandler = mp::internal::NLReader<mp::internal::TextReader<>, mp::internal::VarBoundHandler<mp::internal::NLProblemBuilder<mp::BasicProblem<std::allocator<char> > > > >::VarHandler; Reader = mp::internal::TextReader<>; Handler = mp::internal::VarBoundHandler<mp::internal::NLProblemBuilder<mp::BasicProblem<std::allocator<char> > > >]':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/include/mp/nl-reader.h:1837:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (BoundHandler::TYPE == CON) {
       ^~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/include/mp/nl-reader.h:1850:5: note: here
     default:
     ^~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/include/mp/nl-reader.h: In member function 'void mp::internal::NLReader<Reader, Handler>::ReadBounds() [with BoundHandler = mp::internal::NLReader<mp::internal::TextReader<>, mp::internal::NLProblemBuilder<mp::BasicProblem<std::allocator<char> > > >::VarHandler; Reader = mp::internal::TextReader<>; Handler = mp::internal::NLProblemBuilder<mp::BasicProblem<std::allocator<char> > >]':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/include/mp/nl-reader.h:1837:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (BoundHandler::TYPE == CON) {
       ^~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/include/mp/nl-reader.h:1850:5: note: here
     default:
     ^~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/include/mp/nl-reader.h: In member function 'void mp::internal::NLReader<Reader, Handler>::ReadBounds() [with BoundHandler = mp::internal::NLReader<mp::internal::BinaryReader<mp::internal::IdentityConverter>, mp::internal::VarBoundHandler<mp::internal::NLProblemBuilder<mp::BasicProblem<std::allocator<char> > > > >::VarHandler; Reader = mp::internal::BinaryReader<mp::internal::IdentityConverter>; Handler = mp::internal::VarBoundHandler<mp::internal::NLProblemBuilder<mp::BasicProblem<std::allocator<char> > > >]':
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/include/mp/nl-reader.h:1837:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (BoundHandler::TYPE == CON) {
       ^~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/include/mp/nl-reader.h:1850:5: note: here
     default:
     ^~~~~~~
/builddir/build/BUILD/mp-1f39801af085656e4bf72250356a3a70d5d98e73/include/mp/nl-reader.h: In member function 'void mp::internal::NLReader<Reader, Handler>::ReadBounds() [with BoundHandler = mp::internal::NLReader<mp::internal::BinaryReader<mp::internal::IdentityConverter>, mp::internal::NLProblemBuilder<mp::BasicProblem<std::allocator<char> > > >::VarHandler; Reader = mp::internal::BinaryReader<mp::internal::IdentityConverter>; Handler = mp::internal::NLProblemBuilder<mp::BasicProblem<std::allocator<char> > >]':
```

Full log, [from line #1343](https://paste.fedoraproject.org/paste/okESEMeF0~vp1-53wEvJgF5M1UNdIGYhyRLivL9gydE=/deactivate/UGKtThCJushtUhJO4H0skumou4Mt2Bc751tYNiRBkuTyAZjqfB95kA8159zL2S89)
