### ISSUE TITLE
Compile fails with gsl 2.1

### ISSUE THREAD

**Issue by opoplawski** [ampl/mp#70]
Working on updating gsl to 2.1 in Fedora.  mp fails with:
~~~~~
/builddir/build/BUILD/mp-35060ba2a59f2b0f0fd622ed9df678f142f846ed/src/gsl/amplgsl.c:1493:14: error: too many arguments to function 'gsl_sf_ellint_D_e'
 WRAP_CHECKED(gsl_sf_ellint_D, ARGS3_PREC)
              ^
~~~~~
In gsl 2 they dropped the unused third argument 'n'.  Something like:
~~~~~
#if GSL_MAJOR_VERSION >= 2
WRAP_CHECKED(gsl_sf_ellint_D, ARGS2_PREC)
#else 
WRAP_CHECKED(gsl_sf_ellint_D, ARGS3_PREC)
#endif 
~~~~~
Should work.

**Comment by vitaut** [comment]
I've committed the fix you propose in https://github.com/ampl/mp/commit/eeb32b40141de7f82f4201a608103ef7bc4279b5, but haven't updated gsl yet because it fails to compile on one of the supported platforms (Windows with MSVC). Thanks!

**Comment by vitaut** [comment]
Implemented more fixes and updated gsl module to version 2.1 in https://github.com/ampl/mp/commit/635f5525aeae319a63e97ee26226897dd15ca8bc.

**Comment by opoplawski** [comment]
We have a test failure with gsl 1.16:
~~~~~
[ RUN      ] GSLTest.EllInt
unknown file: Failure
C++ exception with description "invalid number of arguments in function call" thrown in the test body.
[  FAILED  ] GSLTest.EllInt (157 ms)
~~~~~
Works with gsl 2.1 though.

**Comment by vitaut** [comment]
Fixed in https://github.com/ampl/mp/commit/f34afb3bf24ceb51c8fdd6a79ea0b6b6b209dc38, thanks.

**Comment by opoplawski** [comment]
Confirmed, thanks again.
