### ISSUE TITLE
IEEE exception

### ISSUE THREAD

**Issue by dpo** [ampl/mp#57]
Is there a way to compile the ASL so IEEE exceptions return Inf or NaN instead of producing an error? On some Linux machines, IEEE exceptions results in an error message such as "Error while evaluating
objective.", while on OSX, they seem to simply return Inf or NaN.

Thanks.

**Comment by vitaut** [comment]
ASL disables IEEE exceptions unless `ASL_FPINIT_KEEP_TRAPBITS` is defined: https://github.com/ampl/mp/blob/446d11265f8802ca092b4713e20beea55f99b294/src/asl/solvers/fpinit.c#L130-L137

However, the "Error while evaluating objective" is usually reported when a math function returns an error via `errno` and not because of IEEE exceptions: https://github.com/ampl/mp/blob/446d11265f8802ca092b4713e20beea55f99b294/src/asl/solvers/rops2.c#L534

 I'm not sure if you can disable this, but you can handle errors yourself via `asl->i.err_jmp_`.

**Comment by dpo** [comment]
Sorry for the slow reply. I'm observing an erroneous function and gradient values on Linux, but they're ok on OSX. Technically, the evaluation should produce an IEEE error and return +inf. On Linux, I get zero instead.

I'm trying to determine whether the issue comes from ASL or the fact that on Linux, ASL is compiled with gcc (on OSX I use clang by default). When I try to build with gcc 4.9 on OSX, I get the error message

```
mp-2.0.1/src/os.cc:76:12: error: 'strlen' is not a member of 'std'
     size = std::strlen(&buffer[0]);
            ^
```

I added `#include <cstring>` in `os.cc` and everything compiles, but I get a test failure:

```
The following tests FAILED:
	 14 - os-test (Failed)
Errors while running CTest
```

I invoke `cmake` with `-DBUILD_SHARED_LIBS=True -DCMAKE_CXX_COMPILER=g++-4.9 -DCMAKE_C_COMPILER=gcc-4.9`.

Any ideas?

**Comment by vitaut** [comment]
What version do you use? The `strlen` error should be fixed already : https://github.com/ampl/mp/blob/51ae35da4087d2655cb285fabb3707c4bee74bf8/src/os.cc#L29.

Could you post the test log `Testing/Temporary/LastTest.log` that can be found in the build directory?

**Comment by dpo** [comment]
I use version 2.0.1. Somehow the `#include <cstring>` isn't there. I'll try a fresh download.

Here's the test log: https://gist.github.com/f8b120d6bc81cb273f5a

**Comment by vitaut** [comment]
I meant it is fixed in the `master` branch. I can release a minor release with a fix, but let's try to address other issues first.

Strangely I couldn't reproduce the os-test failure on my OS X systems. Could you by any chance post the output of CMake run on a clean mp repo? This could give more info about your setup for me to reproduce the issue.

**Comment by mlubin** [comment]
I just tested with ampl/mp master and the erroneous function value issue isn't resolved on linux.

**Comment by mlubin** [comment]
No apparent difference when compiling with ``-DASL_FPINIT_KEEP_TRAPBITS``.

**Comment by vitaut** [comment]
To clean things up a bit here I've moved the os-test failure to a separate issue (#61) and prepared a corrective release [2.0.2](https://github.com/ampl/mp/releases/tag/2.0.2) that fixes the compilation error on OS X.

Regarding the main issue, as I mentioned in https://github.com/ampl/mp/issues/59#issuecomment-124740934, ASL has macro `WANT_INFNAN` which enables Infinity & NaN propagation. However it only works with some operations at the moment.

**Comment by vitaut** [comment]
@dpo I'm closing this issue since it is possible to enable Infinity propagation at least for some operations with `WANT_INFNAN`, but feel free to reopen if you want some specific operation, which currently doesn't handle `WANT_INFNAN`, to handle it.
